import os
import json
import pickle
import joblib
import pandas as pd
from flask import Flask, jsonify, request
from peewee import (
    SqliteDatabase, Model, IntegerField, FloatField,
    TextField, IntegrityError
)
from playhouse.shortcuts import model_to_dict
from playhouse.db_url import connect

### Database
DB = SqliteDatabase('predictions.db')

class Prediction(Model):
    observation_id = IntegerField(unique=True)
    observation = TextField()
    proba = FloatField()
    true_class = IntegerField(null=True)

    class Meta:
        database = DB

DB.create_tables([Prediction], safe=True)
######

#### Unpickle trained model
with open('columns.json') as fh:
    columns = json.load(fh)

with open('dtypes.pickle', 'rb') as fh:
    dtypes = pickle.load(fh)

pipeline = joblib.load('pipeline.pickle')
####################################################

################# 

def attempt_predict(request):
    """
    Produce prediction for request.
    
    Inputs:
        request: dictionary with the format described below
        {
            "observation_id": <id-as-a-string>,
            "data": {
                "age": <value>,
                "sex": <value>,
                "race": <value>,
                "workclass": <value>,
                "education": <value>,
                "marital-status": <value>,
                "capital-gain": <value>,
                "capital-loss": <value>,
                "hours-per-week": <value>,
            }
        }
     
    Returns: A dictionary with predictions or an error, the two potential values:
                if the request is OK and was properly parsed and predicted:
                {
                    "observation_id": <id-of-request>,
                    "prediction": <True|False>,
                    "probability": <probability generated by model>
                }
                otherwise:
                {
                    "observation_id": <id-of-request>,
                    "error": "some error message"
                }
    """

    # YOUR CODE HERE
    
    # Missing 'observation_id' produces an error
    if 'observation_id' not in request:
        return {
            "error": {
                "observation_id": None,
                "message": f"ID missing from request: {request}"
            }
        }

    # Missing 'data' produces an error
    obs_id = request.get('observation_id')
    if 'data' not in request:
        return {
            "error": {
                "observation_id": obs_id,
                "message": f"Data missing from {request}",
                "data": request  
                }
            }


    # Expected columns
    valid_cols = {"age", "workclass", "sex", "race", "education", "marital-status", "capital-gain", "capital-loss", "hours-per-week"}
        
    data = request.get('data', {})

    keys = set(data.keys())
    missing = valid_cols - keys
    if missing:
        missing_list = sorted(missing)

    # Build clean message
        if len(missing_list) == 1:
            message = f"{missing_list[0]} is missing"
        else:
            message = f"{', '.join(missing_list)} are missing"    
        return {
            "error": {
                "message": message,
                **{col: "missing" for col in missing_list}  
            }
        }

    if len(keys - valid_cols) > 0:
        extra_cols = keys - valid_cols
        return {             
            "error": {
                "message": f"{extra_cols} is not recognized",
                **{col: "missing" for col in extra_cols}  
            }
        }

    valid_category_map = {
        'sex': ['Male', 'Female'],
        'race': ['White', 'Black', 'Asian-Pac-Islander', 'Amer-Indian-Eskimo', 'Other'],
    }

    for key, valid_vals in valid_category_map.items():
        if key in data:
            value = data[key]
            if value not in valid_vals:
                return {
                    "error": {
                        key: "invalid",
                        value: "invalid",   # satisfies your assertion
                        "message": f"{value} not valid as category for {key}"
                    }
                }

    ## Valid values for age 
    age = data.get('age')
    if not age: 
        return {
            'error': "Field 'age' missing"
        }

    if not isinstance(age, int):
        return {
            'error': "Field 'age' is not an integer"
        }
        
    if age < 10 or age > 100:
        return {
            'error': f"Field age is {age} which is not between 10 and 100"
        }


    ## Valid values for "capital-gain"
    capital_gain = data.get("capital-gain")
    capital_loss = data.get('capital-loss')

    if capital_gain < 0:
        return {
            'error': f"Field capital-gain is {capital_gain}"
        }

    ## Valid values for "capital-loss"
    if capital_loss < 0:
        return {
            'error': f"Field capital-loss is {capital_loss}"
        }

    # Valid values for hours per week
    hours_per_week = data.get('hours-per-week')

    if hours_per_week < 0 or hours_per_week > 24*7 :
        return {
            'error': f"Field hours-per-week is {hours_per_week}"
        }
    

    ## If the input is fine
    # Create dataframe
    obs_df = pd.DataFrame([data], columns=columns).astype(dtypes)

    # Prediction
    pred = pipeline.predict(obs_df)[0]

    # Probability 
    proba = pipeline.predict_proba(obs_df)[0, 1]

    response = {
        'observation_id': obs_id,
        **data,
        'prediction': bool(pred),
        'probability': float(proba)
    }

    return response


#################################################################################

### Server
###  Initialize the Flask application
app = Flask(__name__)

# @app.route('/') defines the route for the homepage
@app.route('/predict', methods=['POST'])

### The predict() function is responsible for generating the response
# that the user sees when accessing the '/predict' URL
def predict():
    try:
        obs_dict = request.get_json()
    except Exception:
        return jsonify({"error": "Invalid JSON"}), 400

    ### Run validation + prediction
    response = attempt_predict(obs_dict)

    if "error" in response:
        return jsonify(response), 400
    
    obs_id = response['observation_id']
    proba = response['probability']

    ### Save to database
    try:
        with DB.atomic():
            p = Prediction(
                observation_id = obs_id,
                proba = proba,
                observation = request.data
            )
            p.save()
    except IntegrityError:
        response["error"] = f'Observation id {obs_id} already exists'

    return jsonify(response)


@app.route('/update', methods=['POST'])
def update():
    try:
        obs = request.get_json()
    except Exception:
        return jsonify({'error': 'Invalid JSON'}), 400
    
    try:
        p = Prediction.get(Prediction.observation_id == obs['id'])
        p.true_class = obs['true_class']
        p.save()
        return jsonify(model_to_dict(p))
    
    except Prediction.DoesNotExist:
        return jsonify({'error':  f'Obs id {obs["id"]} does not exist'})
    ###########################################
    
if __name__ == "__main__":
    app.run(host='0.0.0.0', debug=True, port=5000)

